server {
    listen 3000;

    absolute_redirect off;

    root /Users/daniel/Documents/Projects/gloomhaven-storyline/public;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
